from mydivision.pbdraw import PowerBallDraw
from mydivision.ozdraw import OzLottoDraw
from mydivision.pbphdraw import PowerBallPHDraw


class Config(object):
    def __init__(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)


configs = {
    'pb': Config(uri='https://api.thelott.com/sales/vmax/web/data/lotto/latestresults',
                 data={'CompanyId': 'NSWLotteries',
                       'MaxDrawCountPerProduct': 1,
                       'OptionalProductFilter': ['Powerball']},
                 winning_combs={1: {'num_balls': 6,
                                    'needs_powerball': True},
                                2: {'num_balls': 6,
                                    'needs_powerball': False},
                                3: {'num_balls': 5,
                                    'needs_powerball': True},
                                4: {'num_balls': 5,
                                    'needs_powerball': False},
                                5: {'num_balls': 4,
                                    'needs_powerball': True},
                                6: {'num_balls': 3,
                                    'needs_powerball': True},
                                7: {'num_balls': 4,
                                    'needs_powerball': False},
                                8: {'num_balls': 2,
                                    'needs_powerball': True}},
                 cost_per_game=0.92,
                 klass=PowerBallDraw),
    'pbph': Config(uri='https://api.thelott.com/sales/vmax/web/data/lotto/latestresults',
                   data={'CompanyId': 'NSWLotteries',
                         'MaxDrawCountPerProduct': 1,
                         'OptionalProductFilter': ['Powerball']},
                   winning_combs={1: {'num_balls': 6,
                                      'needs_powerball': False},
                                  2: {'num_balls': 6,
                                      'needs_powerball': False},
                                  3: {'num_balls': 5,
                                      'needs_powerball': False},
                                  4: {'num_balls': 5,
                                      'needs_powerball': False},
                                  5: {'num_balls': 4,
                                      'needs_powerball': False},
                                  6: {'num_balls': 3,
                                      'needs_powerball': False},
                                  7: {'num_balls': 4,
                                      'needs_powerball': False},
                                  8: {'num_balls': 2,
                                      'needs_powerball': False}},
                   cost_per_game=18.60,
                   klass=PowerBallPHDraw),
    'oz': Config(uri='https://api.thelott.com/sales/vmax/web/data/lotto/latestresults',
                 data={'CompanyId': 'NSWLotteries',
                       'MaxDrawCountPerProduct': 1,
                       'OptionalProductFilter': ['OzLotto']},
                 winning_combs={1: {'num_balls': 7,
                                    'needs_sups': False},
                                2: {'num_balls': 6,
                                    'needs_sups': True},
                                3: {'num_balls': 6,
                                    'needs_sups': False},
                                4: {'num_balls': 5,
                                    'needs_sups': True},
                                5: {'num_balls': 5,
                                    'needs_sups': False},
                                6: {'num_balls': 4,
                                    'needs_sups': False},
                                7: {'num_balls': 3,
                                    'needs_sups': True}},
                 cost_per_game=1.30,
                 klass=OzLottoDraw)}
